#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

# GETTING-STARTED: change 'db.sqlite3' to your sqlite3 database:
if [ ! -f $OPENSHIFT_DATA_DIR/db.sqlite3 ]
then
	# Copy 'db.sqlite3' to Openshift if not exist already
    # GETTING-STARTED: change 'wagtail-openshift' to your project name and 'db.sqlite3' to the name of your sqlite3 database:
	echo "Copying $OPENSHIFT_REPO_DIR/wsgi/wagtail-openshift/db.sqlite3 to $OPENSHIFT_DATA_DIR"
    # GETTING-STARTED: change 'wagtail-openshift' to your project name and 'db.sqlite3' to the name of your sqlite3 database:
	cp "$OPENSHIFT_REPO_DIR"wsgi/wagtail-openshift/db.sqlite3 $OPENSHIFT_DATA_DIR
else
    # GETTING-STARTED: change 'wagtail-openshift' to your project name:
	echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/wagtail-openshift/manage.py makemigrations'"
    # GETTING-STARTED: change 'wagtail-openshift' to your project name:
	python "$OPENSHIFT_REPO_DIR"wsgi/wagtail-openshift/manage.py makemigrations
    # GETTING-STARTED: change 'wagtail-openshift' to your project name:
	echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/wagtail-openshift/manage.py migrate'"
    # GETTING-STARTED: change 'wagtail-openshift' to your project name:
	python "$OPENSHIFT_REPO_DIR"wsgi/wagtail-openshift/manage.py migrate
fi

# GETTING-STARTED: change 'wagtail-openshift' to your project name:
echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/wagtail-openshift/manage.py collectstatic --noinput --link'"
# GETTING-STARTED: change 'wagtail-openshift' to your project name:
python "$OPENSHIFT_REPO_DIR"wsgi/wagtail-openshift/manage.py collectstatic --noinput --link
